---
- hosts: 192.168.118.130
  sudo: yes
  vars:
  tasks:
        - block:
                - name: Installing Apache on Nodes
                  yum:
                        name: "{{ web_package }}"
                        state: latest
          rescue:
                - name: Installing Telnet
                  yum:
                        name: "{{ remote_access }}"
                        state: latest
          always:
                - name: Running Always
                  yum:
                        name: "{{ one_more }}"
                        state: latest
